### ISSUE TITLE
All godot file types can't be inserted as notes

### ISSUE THREAD

**Issue by ipeerbhai** [turnrocklabs/Minerva#103]
Cannot insert .tscn files or .godot files into the notes or open with File --> Open.
Can you please add these 2 file types to the allowed list?

**Comment by VampireSqu1d** [comment]
bug fixed in user/cuauh/bug/saveAs branch, I'll close the issue when we merge it into development

**Comment by VampireSqu1d** [comment]
.tscn, .godot and .gd are now supported
