### ISSUE TITLE
Save/Save As poor user experience

### ISSUE THREAD

**Issue by ipeerbhai** [turnrocklabs/Minerva#105]
Two issues:
1. File names are wrong.  The file extension loses the first letter. "project.godot" becomes "project.odot" for any type of file.
2. Period in the filename should mean "user is specifying extension, don't check".
3. Don't force the user to enter a filename with a "." at the end.  Right now, user needs to enter "project.", then select "godot" from the drop down.  User should enter just "project" with no "." character -OR- if the user enters a "." character, then assume the user knows the extension and don't double check the name.
4. Save As always re-opens in the Program's working director.  Instead, have both "Save" and "Save As" track what directory was last used, and start there.

**Comment by VampireSqu1d** [comment]
this change is fixed
