### ISSUE TITLE
Terminal hangs after some time

### ISSUE THREAD

**Issue by ipeerbhai** [turnrocklabs/Minerva#118]
Terminal won't run any more processes / hangs after a while.
Don't know if it's time or scroll.  I scrolled up to read the output, then went to make a new run of godot--verbose.
The terminal stopped working -- Godot won't launch, nor does "ls" or any command work any longer.

It worked for a long time before hitting this state.

**Comment by DzIGIBAUER** [comment]
This was probably caused by large amount of text in output label. I'm not sure when exactly this was resolved, but it seems it's not a problem anymore.
