### ISSUE TITLE
Reload Editor Window doesn't send updates

### ISSUE THREAD

**Issue by ipeerbhai** [turnrocklabs/Minerva#132]
Load a file in an editor window.
Change the file in a different app ( like VSCode ).
Hit the "reload" button in Minerva. Text will be updated.
Send the reloaded information to the LLM.

The LLM won't get the newest version, and will complain that suggested changes weren't made in the file.

Closing the editor tab and loading the file again from disk, then sending to LLM, will work fine.  Only "reload" text won't update in LLM.

**Comment by DzIGIBAUER** [comment]
Fixed by 6827f1d30346c5cfacc6561ac34ea500db9478e4
