### ISSUE TITLE
Application crash on delete notes tab

### ISSUE THREAD

**Issue by BrenanL** [turnrocklabs/Minerva#80]
## Repro:
1. Create and then delete a notes tab

> Invalid type in function 'store_deleted_tab_right' in base 'Node (undoMain)'. The Object-derived class of argument 2 (previously freed) is not a subclass of the expected argument class.

func _on_close_tab(tab: int, container: TabContainer):
	var control = container.get_tab_control(tab)
	
	# This is the thread index in the list, not it's id
	var thread_idx = SingletonObject.ThreadList.find(control.get_meta("thread"))
	if thread_idx != -1:
		# Remove the thread from the list
		SingletonObject.ThreadList.remove_at(thread_idx)

		# Update the UI with the remaining threads
		render_threads()

		# Store deleted tab for potential undo
		SingletonObject.undo.store_deleted_tab_right(tab, control, "right")
	
	# Remove the tab control from the TabContainer
	container.remove_child(control) 

Stack trace: at line *SingletonObject.undo.store_deleted_tab_right(tab, control, "right")* control is null

**Comment by DzIGIBAUER** [comment]
fixed
