### ISSUE TITLE
terminal breaks on python

### ISSUE THREAD

**Issue by VampireSqu1d** [turnrocklabs/Minerva#91]
=========================Godot output=========================================== 
Running: C:\WINDOWS\system32\cmd.exe /V:ON /C cd /d C:/Users/cuauh/AppData/Roaming && python & echo ##cwd##!cd!

I typed `python` on the terminal and it returns nothing and wont let you type anything else.

Expected output
============Powershell output==========================================
PS C:\Users\cuauh> python
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by DzIGIBAUER** [comment]
Reading/writing to stdin is not supported in Godot 4.2, so we'll either have to wait for Godot 4.3 which is currently in beta or make some hacky workaround with files on filesystem that simulate a stdin stream.
So until then, commands that require handling post run input can't work.

**Comment by DzIGIBAUER** [comment]
Since 4.3 this is not a Godot issue anymore.
New terminal is on [user/milos/feature/terminal](https://github.com/turnrocklabs/Minerva/tree/user/milos/feature/terminal), but the check buttons for including terminal output in chat is not implemented yet.

**Comment by DzIGIBAUER** [comment]
Okay, interactive commands work now. python shell works only if ran using the `python -i` command.
(https://stackoverflow.com/questions/66763957/python-interactive-shell-not-responding-to-input-when-run-in-subprocess)
But even if user gets stuck in regular python shell, or any other that may not be working, they can Ctrl+C to terminate it.
